##===- lib/utils/Makefile ----------------------*- Makefile -*-===##

#
# Relative path to the top of the source tree.
#
LEVEL=../..

#
# Give the name of the library
#
LIBRARYNAME=Utils

#
# Include Makefile common so we know what to do. 
#
include $(LEVEL)/Makefile.common
